In [24]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import dask.dataframe as de

In [39]:
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

y2015.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,68009401,72868139.0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,C5,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,68354783,73244544.0,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,A4,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,68466916,73356753.0,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,A4,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,68466961,73356799.0,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,A2,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,68495092,73384866.0,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,E3,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0

In [40]:
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util', 
         'sub_grade', 'addr_state', 'id', 'member_id', 'num_tl_90g_dpd_24m','num_tl_op_past_12m'], 1, inplace=True)

In [41]:
y2015.tail()

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,...,num_tl_120dpd_2m,num_tl_30dpd,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
421092,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,5 years,RENT,35000.0,...,0.0,0.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,1 year,RENT,64400.0,...,0.0,0.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,10+ years,RENT,100000.0,...,0.0,0.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [42]:
y2015 = y2015[:-2]

In [43]:
pd.get_dummies(y2015)

,loan_amnt,funded_amnt,funded_amnt_inv,installment,annual_inc,dti,delinq_2yrs,inq_last_6mths,mths_since_last_delinq,mths_since_last_record,...,last_credit_pull_d_Nov-2016,last_credit_pull_d_Oct-2015,last_credit_pull_d_Oct-2016,last_credit_pull_d_Sep-2015,last_credit_pull_d_Sep-2016,application_type_INDIVIDUAL,application_type_JOINT,verification_status_joint_Not Verified,verification_status_joint_Source Verified,verification_status_joint_Verified
0,16000.0,16000.0,16000.0,379.39,48000.0,33.18,0.0,0.0,33.0,2.0,...,0,0,0,0,0,1,0,0,0,0
1,9600.0,9600.0,9600.0,298.58,60000.0,22.44,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
2,25000.0,25000.0,25000.0,777.55,109000.0,26.02,0.0,1.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
3,28000.0,28000.0,28000.0,858.05,92000.0,21.60,0.0,0.0,42.0,NaN,...,0,0,0,0,0,1,0,0,0,0
4,8650.0,8650.0,8650.0,320.99,55000.0,25.49,0.0,4.0,NaN,30.0,...,0,0,0,0,0,1,0,0,0,0
5,23000.0,23000.0,23000.0,471.77,64000.0,18.28,0.0,0.0,29.0,NaN,...,0,0,0,0,0,1,0,0,0,0
6,29900.0,29900.0,29900.0,678.49,65000.0,21.77,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
7,18000.0,18000.0,18000.0,400.31,112000.0,8.68,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
8,35000.0,35000.0,35000.0,829.90,110000.0,17.06,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
9,10400.0,10400.0,10400.0,289.91,104433.0,25.37,1.0,3.0,12.0,NaN,...,0,0,0,0,0,1,0,0,0,0
10,20000.0,20000.0,20000.0,432.66,63000.0,10.78,0.0,0.0,NaN,NaN,...,0,0,0,0,0,0,1,1,0,0
11,22400.0,22400.0,22400.0,508.30,95000.0,22.98,0.0,0.0,54.0,NaN,...,0,0,0,0,0,1,0,0,0,0
12,16000.0,16000.0,16000.0,363.07,70000.0,26.40,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
13,3600.0,3600.0,3600.0,123.03,55000.0,5.91,0.0,1.0,30.0,NaN,...,0,0,0,0,0,1,0,0,0,0
14,24700.0,24700.0,24700.0,820.28,65000.0,16.06,1.0,4.0,6.0,NaN,...,0,0,0,0,0,1,0,0,0,0
15,10000.0,10000.0,10000.0,306.45,85000.0,13.07,0.0,1.0,NaN,106.0,...,0,0,0,0,0,1,0,0,0,0
16,1400.0,1400.0,1400.0,47.10,64000.0,34.95,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
17,11950.0,11950.0,11950.0,405.18,34000.0,10.20,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
18,18000.0,18000.0,18000.0,471.70,150000.0,9.39,0.0,1.0,NaN,75.0,...,0,0,0,0,0,1,0,0,0,0
19,8000.0,8000.0,8000.0,263.74,42000.0,34.80,0.0,0.0,75.0,NaN,...,0,0,0,0,0,1,0,0,0,0
20,20000.0,20000.0,20000.0,631.26,85000.0,17.61,1.0,0.0,3.0,NaN,...,0,0,0,0,0,1,0,0,0,0
21,20000.0,20000.0,20000.0,637.58,180000.0,14.67,0.0,0.0,49.0,NaN,...,1,0,0,0,0,1,0,0,0,0
22,28000.0,28000.0,28000.0,949.38,125000.0,7.49,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
23,5000.0,5000.0,5000.0,169.54,79000.0,12.70,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
24,20000.0,20000.0,20000.0,602.30,65000.0,18.83,0.0,1.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
25,4225.0,4225.0,4225.0,146.16,35000.0,15.22,2.0,0.0,18.0,NaN,...,0,0,0,0,0,1,0,0,0,0
26,15000.0,15000.0,15000.0,451.73,44000.0,15.34,0.0,1.0,47.0,NaN,...,0,0,0,0,0,1,0,0,0,0
27,17600.0,17600.0,17600.0,530.03,88000.0,26.59,0.0,0.0,NaN,NaN,...,1,0,0,0,0,1,0,0,0,0
28,6000.0,6000.0,6000.0,186.61,100000.0,13.28,1.0,1.0,15.0,NaN,...,0,0,0,0,0,1,0,0,0,0
29,16000.0,16000.0,16000.0,538.18,65000.0,18.96,0.0,0.0,33.0,66.0,...,0,0,0,0,0,1,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421065,13000.0,13000.0,13000.0,408.52,85000.0,8.05,1.0,0.0,15.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421066,15000.0,15000.0,15000.0,498.15,70000.0,8.47,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421067,20000.0,20000.0,20000.0,617.46,72000.0,27.24,0.0,1.0,69.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421068,4200.0,4200.0,4200.0,147.64,48000.0,36.93,0.0,0.0,38.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421069,26950.0,26950.0,26950.0,846.88,54000.0,18.11,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421070,23000.0,23000.0,23000.0,554.32,50000.0,31.95,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421071,18700.0,18700.0,18700.0,473.44,52000.0,11.28,0.0,0.0,30.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421072,6000.0,6000.0,6000.0,216.50,90000.0,2.84,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421073,15000.0,15000.0,15000.0,329.44,57000.0,15.77,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421074,25000.0,25000.0,25000.0,607.82,103000.0,5.27,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421075,26500.0,26500.0,26500.0,545.87,92000.0,29.60,1.0,0.0,17.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421076,25000.0,25000.0,25000.0,602.52,55000.0,5.52,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421077,21000.0,21000.0,21000.0,639.15,65000.0,17.09,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421078,8000.0,8000.0,8000.0,251.40,50000.0,17.62,0.0,1.0,24.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421079,12000.0,12000.0,12000.0,384.34,40000.0,25.65,1.0,0.0,8.0,NaN,...,0,0,1,0,0,1,0,0,0,0
421080,10000.0,10000.0,10000.0,306.45,75000.0,33.66,0.0,0.0,29.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421081,13150.0,13150.0,13150.0,312.77,30000.0,1.00,0.0,0.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421082,6225.0,6225.0,6225.0,220.37,27000.0,18.58,0.0,1.0,NaN,NaN,...,0,0,0,0,0,1,0,0,0,0
421083,10775.0,10775.0,10775.0,327.95,54000.0,13.22,1.0,0.0,16.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421084,7000.0,7000.0,7000.0,240.30,57000.0,16.80,2.0,3.0,10.0,52.0,...,0,0,0,0,0,1,0,0,0,0
421085,4000.0,4000.0,4000.0,126.59,50000.0,12.63,0.0,0.0,NaN,84.0,...,0,0,1,0,0,1,0,0,0,0
421086,7500.0,7500.0,7500.0,240.22,40000.0,25.63,0.0,0.0,69.0,88.0,...,0,0,0,0,0,1,0,0,0,0
421087,10850.0,10850.0,10850.0,399.04,32000.0,29.44,0.0,1.0,65.0,NaN,...,0,0,1,0,0,1,0,0,0,0
421088,11575.0,11575.0,11575.0,404.61,25400.0,27.08,0.0,0.0,NaN,NaN,...,1,0,0,0,0,1,0,0,0,0
421089,12000.0,12000.0,12000.0,398.52,63000.0,23.69,1.0,0.0,9.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421090,10000.0,10000.0,10000.0,332.10,31000.0,28.69,0.0,0.0,NaN,77.0,...,0,0,0,0,0,1,0,0,0,0
421091,24000.0,24000.0,24000.0,797.03,79000.0,3.90,0.0,1.0,26.0,NaN,...,0,0,0,0,0,1,0,0,0,0
421092,13000.0,13000.0,13000.0,316.07,35000.0,30.90,0.0,0.0,NaN,84.0,...,0,0,0,0,0,1,0,0,0,0
421093,12000.0,12000.0,12000.0,317.86,64400.0,27.19,1.0,2.0,22.0,NaN,...,0,0,1,0,0,1,0,0,0,0
421094,20000.0,20000.0,20000.0,664.20,100000.0,10.83,0.0,1.0,NaN,110.0,...,0,0,0,0,0,1,0,0,0,0

In [44]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

# cross_val_score(rfc, X, Y, cv=10)

c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\rjourney\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:245: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)

array([0.98095509, 0.98031393, 0.98157251, 0.98185747, 0.9777725 ,
       0.98057469, 0.97169251, 0.98038424, 0.98014582, 0.98031159])

In [22]:
df.columns

Index(['loan_amnt', 'funded_amnt', 'funded_amnt_inv', 'term', 'int_rate',
       'installment', 'grade', 'emp_length', 'home_ownership', 'annual_inc',
       ...
       'num_tl_90g_dpd_24m', 'num_tl_op_past_12m', 'pct_tl_nvr_dlq',
       'percent_bc_gt_75', 'pub_rec_bankruptcies', 'tax_liens',
       'tot_hi_cred_lim', 'total_bal_ex_mort', 'total_bc_limit',
       'total_il_high_credit_limit'],
      dtype='object', length=102)

In [23]:
df = df.replace("<", "")

,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,emp_length,home_ownership,annual_inc,...,num_tl_90g_dpd_24m,num_tl_op_past_12m,pct_tl_nvr_dlq,percent_bc_gt_75,pub_rec_bankruptcies,tax_liens,tot_hi_cred_lim,total_bal_ex_mort,total_bc_limit,total_il_high_credit_limit
0,16000.0,16000.0,16000.0,60 months,14.85%,379.39,C,10+ years,MORTGAGE,48000.0,...,0.0,2.0,78.9,0.0,0.0,2.0,298100.0,31329.0,281300.0,13400.0
1,9600.0,9600.0,9600.0,36 months,7.49%,298.58,A,8 years,MORTGAGE,60000.0,...,0.0,2.0,100.0,66.7,0.0,0.0,88635.0,55387.0,12500.0,75635.0
2,25000.0,25000.0,25000.0,36 months,7.49%,777.55,A,10+ years,MORTGAGE,109000.0,...,0.0,0.0,100.0,20.0,0.0,0.0,373572.0,68056.0,38400.0,82117.0
3,28000.0,28000.0,28000.0,36 months,6.49%,858.05,A,10+ years,MORTGAGE,92000.0,...,0.0,0.0,91.7,22.2,0.0,0.0,304003.0,74920.0,41500.0,42503.0
4,8650.0,8650.0,8650.0,36 months,19.89%,320.99,E,8 years,RENT,55000.0,...,0.0,12.0,100.0,50.0,1.0,0.0,38998.0,18926.0,2750.0,18248.0
5,23000.0,23000.0,23000.0,60 months,8.49%,471.77,B,5 years,RENT,64000.0,...,0.0,2.0,87.9,14.3,0.0,0.0,93962.0,63886.0,39500.0,46662.0
6,29900.0,29900.0,29900.0,60 months,12.88%,678.49,C,10+ years,MORTGAGE,65000.0,...,0.0,4.0,100.0,25.0,0.0,0.0,271700.0,42497.0,34000.0,15574.0
7,18000.0,18000.0,18000.0,60 months,11.99%,400.31,C,10+ years,MORTGAGE,112000.0,...,0.0,4.0,100.0,0.0,0.0,0.0,309710.0,36127.0,69800.0,26210.0
8,35000.0,35000.0,35000.0,60 months,14.85%,829.90,C,10+ years,MORTGAGE,110000.0,...,0.0,1.0,100.0,0.0,0.0,0.0,381215.0,52226.0,62500.0,18000.0
9,10400.0,10400.0,10400.0,60 months,22.45%,289.91,F,3 years,MORTGAGE,104433.0,...,0.0,4.0,96.6,60.0,0.0,0.0,439570.0,95768.0,20300.0,88097.0
10,20000.0,20000.0,20000.0,60 months,10.78%,432.66,B,10+ years,MORTGAGE,63000.0,...,0.0,0.0,100.0,50.0,0.0,0.0,218418.0,18696.0,6200.0,14877.0
11,22400.0,22400.0,22400.0,60 months,12.88%,508.30,C,6 years,MORTGAGE,95000.0,...,0.0,3.0,97.0,25.0,0.0,0.0,436841.0,184356.0,21000.0,191682.0
12,16000.0,16000.0,16000.0,60 months,12.88%,363.07,C,1 year,MORTGAGE,70000.0,...,0.0,1.0,100.0,60.0,0.0,0.0,309638.0,62407.0,45900.0,45838.0
13,3600.0,3600.0,3600.0,36 months,13.99%,123.03,C,10+ years,MORTGAGE,55000.0,...,0.0,3.0,76.9,0.0,0.0,0.0,178050.0,7746.0,2400.0,13734.0
14,24700.0,24700.0,24700.0,36 months,11.99%,820.28,C,10+ years,MORTGAGE,65000.0,...,0.0,2.0,97.4,7.7,0.0,0.0,314017.0,39475.0,79300.0,24667.0
15,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,6 years,RENT,85000.0,...,0.0,2.0,95.7,28.6,1.0,0.0,61099.0,27957.0,16400.0,30799.0
16,1400.0,1400.0,1400.0,36 months,12.88%,47.10,C,3 years,MORTGAGE,64000.0,...,0.0,1.0,100.0,75.0,0.0,0.0,372109.0,75258.0,34500.0,55501.0
17,11950.0,11950.0,11950.0,36 months,13.44%,405.18,C,4 years,RENT,34000.0,...,0.0,0.0,100.0,100.0,0.0,0.0,16900.0,12798.0,9400.0,4000.0
18,18000.0,18000.0,18000.0,60 months,19.48%,471.70,E,7 years,RENT,150000.0,...,0.0,3.0,100.0,14.3,1.0,0.0,65819.0,36247.0,10300.0,31319.0
19,8000.0,8000.0,8000.0,36 months,11.48%,263.74,B,10+ years,MORTGAGE,42000.0,...,0.0,2.0,94.4,33.3,0.0,0.0,256513.0,113782.0,17000.0,135513.0
20,20000.0,20000.0,20000.0,36 months,8.49%,631.26,B,10+ years,MORTGAGE,85000.0,...,1.0,0.0,93.3,0.0,0.0,0.0,193390.0,27937.0,14500.0,36144.0
21,20000.0,20000.0,20000.0,36 months,9.17%,637.58,B,10+ years,MORTGAGE,180000.0,...,0.0,2.0,96.3,100.0,0.0,0.0,388852.0,116762.0,31500.0,46452.0
22,28000.0,28000.0,28000.0,36 months,13.44%,949.38,C,2 years,OWN,125000.0,...,0.0,0.0,100.0,40.0,0.0,0.0,36100.0,22780.0,29000.0,0.0
23,5000.0,5000.0,5000.0,36 months,13.44%,169.54,C,2 years,RENT,79000.0,...,0.0,0.0,100.0,100.0,0.0,0.0,41091.0,35653.0,4300.0,31791.0
24,20000.0,20000.0,20000.0,36 months,5.32%,602.30,A,9 years,OWN,65000.0,...,0.0,0.0,100.0,0.0,0.0,0.0,106217.0,15444.0,76200.0,30017.0
25,4225.0,4225.0,4225.0,36 months,14.85%,146.16,C,5 years,RENT,35000.0,...,0.0,0.0,66.7,0.0,0.0,0.0,21822.0,4888.0,2600.0,17522.0
26,15000.0,15000.0,15000.0,36 months,5.32%,451.73,A,10+ years,MORTGAGE,44000.0,...,0.0,0.0,90.5,0.0,0.0,0.0,33800.0,17003.0,14300.0,0.0
27,17600.0,17600.0,17600.0,36 months,5.32%,530.03,A,< 1 year,MORTGAGE,88000.0,...,0.0,1.0,100.0,0.0,0.0,0.0,285027.0,80847.0,23600.0,92701.0
28,6000.0,6000.0,6000.0,36 months,7.49%,186.61,A,10+ years,MORTGAGE,100000.0,...,0.0,0.0,93.7,50.0,0.0,0.0,156354.0,22741.0,3800.0,36083.0
29,16000.0,16000.0,16000.0,36 months,12.88%,538.18,C,10+ years,MORTGAGE,65000.0,...,0.0,2.0,80.0,0.0,0.0,1.0,80999.0,39781.0,4700.0,71499.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421067,20000.0,20000.0,20000.0,36 months,6.99%,617.46,A,2 years,MORTGAGE,72000.0,...,0.0,4.0,80.0,50.0,0.0,0.0,423079.0,52677.0,26700.0,46379.0
421068,4200.0,4200.0,4200.0,36 months,15.99%,147.64,D,10+ years,MORTGAGE,48000.0,...,0.0,6.0,88.9,100.0,0.0,0.0,224211.0,45512.0,5600.0,40401.0
421069,26950.0,26950.0,26950.0,36 months,8.19%,846.88,A,NaN,RENT,54000.0,...,0.0,0.0,100.0,0.0,0.0,0.0,137433.0,41650.0,124600.0,8333.0
421070,23000.0,23000.0,23000.0,60 months,15.59%,554.32,D,10+ years,MORTGAGE,50000.0,...,0.0,2.0,100.0,37.5,0.0,0.0,79510.0,48978.0,60800.0,13910.0
421071,18700.0,18700.0,18700.0,60 months,17.86%,473.44,D,10+ years,RENT,52000.0,...,0.0,3.0,88.9,50.0,0.0,0.0,42499.0,40164.0,10000.0,32299.0
421072,6000.0,6000.0,6000.0,36 months,17.86%,216.50,D,10+ years,MORTGAGE,90000.0,...,0.0,2.0,100.0,100.0,0.0,0.0,412963.0,14906.0,1900.0,8085.0
421073,15000.0,15000.0,15000.0,60 months,11.44%,329.44,B,4 years,RENT,57000.0,...,0.0,2.0,100.0,40.0,0.0,0.0,47674.0,33529.0,22500.0,21574.0
421074,25000.0,25000.0,25000.0,60 months,15.99%,607.82,D,3 years,RENT,103000.0,...,0.0,0.0,100.0,100.0,0.0,0.0,18700.0,17275.0,17500.0,0.0
421075,26500.0,26500.0,26500.0,60 months,8.67%,545.87,B,10+ years,MORTGAGE,92000.0,...,0.0,0.0,95.2,50.0,0.0,0.0,214551.0,91768.0,67600.0,33501.0
421076,25000.0,25000.0,25000.0,60 months,15.59%,602.52,D,NaN,OWN,55000.0,...,0.0,1.0,100.0,37.5,0.0,0.0,24400.0,13860.0,20900.0,0.0
421077,21000.0,21000.0,21000.0,36 months,6.03%,639.15,A,10+ years,MORTGAGE,65000.0,...,0.0,0.0,100.0,0.0,0.0,0.0,301457.0,36303.0,76300.0,36656.0
421078,8000.0,8000.0,8000.0,36 months,8.19%,251.40,A,9 years,MORTGAGE,50000.0,...,0.0,2.0,85.2,33.3,0.0,0.0,230732.0,38259.0,5800.0,39940.0
421079,12000.0,12000.0,12000.0,36 months,9.49%,384.34,B,4 years,RENT,40000.0,...,1.0,1.0,80.0,40.0,0.0,0.0,28183.0,20671.0,10500.0,16283.0
421080,10000.0,10000.0,10000.0,36 months,6.49%,306.45,A,1 year,RENT,75000.0,...,0.0,0.0,96.9,0.0,0.0,0.0,148298.0,88120.0,30300.0,117998.0
421081,13150.0,13150.0,13150.0,60 months,14.99%,312.77,C,8 years,MORTGAGE,30000.0,...,0.0,0.0,100.0,0.0,0.0,0.0,190700.0,672.0,20700.0,0.0
421082,6225.0,6225.0,6225.0,36 months,16.49%,220.37,D,2 years,RENT,27000.0,...,0.0,0.0,100.0,100.0,0.0,0.0,14307.0,8357.0,1800.0,12507.0
421083,10775.0,10775.0,10775.0,36 months,6.03%,327.95,A,< 1 year,RENT,54000.0,...,0.0,0.0,90.5,0.0,0.0,0.0,60948.0,24696.0,38700.0,19248.0
421084,7000.0,7000.0,7000.0,36 months,14.31%,240.30,C,10+ years,RENT,57000.0,...,1.0,3.0,80.0,16.7,0.0,2.0,43768.0,32135.0,6900.0,33868.0
421085,4000.0,4000.0,4000.0,36 months,8.67%,126.59,B,10+ years,MORTGAGE,50000.0,...,0.0,2.0,100.0,0.0,1.0,0.0,58334.0,18979.0,12900.0,28234.0
421086,7500.0,7500.0,7500.0,36 months,9.49%,240.22,B,8 years,RENT,40000.0,...,0.0,4.0,96.6,20.0,1.0,0.0,36320.0,18611.0,10700.0,21820.0
421087,10850.0,10850.0,10850.0,36 months,19.24%,399.04,E,NaN,OWN,32000.0,...,0.0,3.0,90.0,50.0,0.0,0.0,81797.0,28301.0,2500.0,27533.0
421088,11575.0,11575.0,11575.0,36 months,15.59%,404.61,D,10+ years,RENT,25400.0,...,0.0,1.0,100.0,42.9,0.0,0.0,29866.0,19798.0,27500.0,1766.0
421089,12000.0,12000.0,12000.0,36 months,11.99%,398.52,B,< 1 year,MORTGAGE,63000.0,...,1.0,3.0,98.3,50.0,0.0,0.0,325484.0,112990.0,15400.0,98125.0
421090,10000.0,10000.0,10000.0,36 months,11.99%,332.10,B,8 years,RENT,31000.0,...,0.0,1.0,100.0,100.0,0.0,0.0,32950.0,25274.0,9200.0,15850.0
421091,24000.0,24000.0,24000.0,36 months,11.99%,797.03,B,10+ years,MORTGAGE,79000.0,...,0.0,2.0,56.5,100.0,0.0,0.0,152650.0,8621.0,9000.0,0.0
421092,13000.0,13000.0,13000.0,60 months,15.99%,316.07,D,5 years,RENT,35000.0,...,0.0,3.0,100.0,50.0,1.0,0.0,51239.0,34178.0,10600.0,33239.0
421093,12000.0,12000.0,12000.0,60 months,19.99%,317.86,E,1 year,RENT,64400.0,...,1.0,2.0,95.0,66.7,0.0,0.0,96919.0,58418.0,9700.0,69919.0
421094,20000.0,20000.0,20000.0,36 months,11.99%,664.20,B,10+ years,RENT,100000.0,...,0.0,1.0,100.0,50.0,0.0,1.0,43740.0,33307.0,41700.0,0.0
421095,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
421096,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN